version: '3.4'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weborders
    ports:
      - '3307:3306'
#    volumes:
#      - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql
