### Login

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "bruce",
  "password": "1234"
}

> {% client.global.set("auth_token", response.body.token); %}

### Me

GET http://localhost:3000/api/user/me
Authorization: Bearer {{auth_token}}

### Create a client

POST http://localhost:3000/api/client
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Test"
}
