### Login

POST {{api}}/auth/login
Content-Type: application/json

{
  "username": "bruce",
  "password": "1234"
}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.global.set("auth_token", response.body.token);
%}

### Create a brand

POST {{api}}/brand
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Test",
  "red": 100,
  "green": 100,
  "blue": 100
}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.global.set('brand', response.body.id);
%}

### Get the created brand

GET {{api}}/brand/{{brand}}
Authorization: Bearer {{auth_token}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Brand id is right", function() {
    client.assert(Number(response.body.id) === Number(client.global.get('brand')));
  });
%}

### Get all brands

GET {{api}}/brand
Authorization: Bearer {{auth_token}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Brand is in response", function() {
    client.assert(response.body.items.filter(function(item) {
      return Number(item.id) === Number(client.global.get('brand'))
    }).length === 1);
  });
  client.test("Brand is first item", function() {
    client.assert(Number(response.body.items[0].id) === Number(client.global.get('brand')));
  });
%}

### Delete the created brand

DELETE {{api}}/brand/{{brand}}
Authorization: Bearer {{auth_token}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### Get the deleted brand

GET {{api}}/brand/{{brand}}
Authorization: Bearer {{auth_token}}

> {%
  client.test("Not found", function() {
    client.assert(response.status === 404, "Response status is not 404");
  });
%}
