### Login

POST {{api}}/auth/login
Content-Type: application/json

{
  "username": "bruce",
  "password": "1234"
}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.global.set("auth_token", response.body.token);
%}

### Create an invalid color - red too big

POST {{api}}/color
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Test",
  "red": 256,
  "green": 100,
  "blue": 100
}

> {%
  client.test("Request error", function() {
    client.assert(response.status === 400, "Response status is not 400");
  });
%}

### Create a color

POST {{api}}/color
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Test",
  "red": 100,
  "green": 100,
  "blue": 100
}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.global.set('color', response.body.id);
%}

### Get the created color

GET {{api}}/color/{{color}}
Authorization: Bearer {{auth_token}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Color id is right", function() {
    client.assert(Number(response.body.id) === Number(client.global.get('color')));
  });
%}

### Get all colors

GET {{api}}/color
Authorization: Bearer {{auth_token}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Color is in response", function() {
    client.assert(response.body.items.filter(function(item) {
      return Number(item.id) === Number(client.global.get('color'))
    }).length === 1);
  });
  client.test("Color is first item", function() {
    client.assert(Number(response.body.items[0].id) === Number(client.global.get('color')));
  });
%}

### Delete the created color

DELETE {{api}}/color/{{color}}
Authorization: Bearer {{auth_token}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### Get the deleted color

GET {{api}}/color/{{color}}
Authorization: Bearer {{auth_token}}

> {%
  client.test("Not found", function() {
    client.assert(response.status === 404, "Response status is not 404");
  });
%}
