### Login

POST {{api}}/auth/login
Content-Type: application/json

{
  "username": "bruce",
  "password": "1234"
}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.global.set("auth_token", response.body.token);
%}

### Create a component with a color

POST {{api}}/component
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Test",
  "color": 1
}

### Create a component without a color

POST {{api}}/component
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Test"
}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.global.set('component', response.body.id);
%}

### Get the created component

GET {{api}}/component/{{component}}
Authorization: Bearer {{auth_token}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Component id is right", function() {
    client.assert(Number(response.body.id) === Number(client.global.get('component')));
  });
%}

### Get all components

GET {{api}}/component
Authorization: Bearer {{auth_token}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Component is in response", function() {
    client.assert(response.body.items.filter(function(item) {
      return Number(item.id) === Number(client.global.get('component'))
    }).length === 1);
  });
  client.test("Component is first item", function() {
    client.assert(Number(response.body.items[0].id) === Number(client.global.get('component')));
  });
%}

### Delete the created component

DELETE {{api}}/component/{{component}}
Authorization: Bearer {{auth_token}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### Get the deleted component

GET {{api}}/component/{{component}}
Authorization: Bearer {{auth_token}}

> {%
  client.test("Not found", function() {
    client.assert(response.status === 404, "Response status is not 404");
  });
%}
