### Login

POST {{api}}/auth/login
Content-Type: application/json

{
  "username": "bruce",
  "password": "1234"
}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.global.set("auth_token", response.body.token);
%}

### Create a shoe model

POST {{api}}/shoe-model
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Test",
  "type": "",
  "components": []
}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.global.set('shoe-model', response.body.id);
%}

### Create a shoe model

POST {{api}}/shoe-model
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Test",
  "type": "",
  "components": [1, 2, 3]
}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.global.set('shoe-model', response.body.id);
%}

### Get the created shoe model

GET {{api}}/shoe-model/{{shoe-model}}
Authorization: Bearer {{auth_token}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Shoe Model id is right", function() {
    client.assert(Number(response.body.id) === Number(client.global.get('shoe-model')));
  });
%}

### Get all shoe models

GET {{api}}/shoe-model
Authorization: Bearer {{auth_token}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Shoe Model is in response", function() {
    client.assert(response.body.items.filter(function(item) {
      return Number(item.id) === Number(client.global.get('shoe-model'))
    }).length === 1);
  });
  client.test("Shoe Model is first item", function() {
    client.assert(Number(response.body.items[0].id) === Number(client.global.get('shoe-model')));
  });
%}

### Delete the created shoe model

DELETE {{api}}/shoe-model/{{shoe-model}}
Authorization: Bearer {{auth_token}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### Get the deleted shoe model

GET {{api}}/shoe-model/{{shoe-model}}
Authorization: Bearer {{auth_token}}

> {%
  client.test("Not found", function() {
    client.assert(response.status === 404, "Response status is not 404");
  });
%}
